services:
  backend:
    build: ./backend
    volumes:
       - ./backend/app:/app/app
       - ./test_project:/code/
       - ./backend/ruff.toml:/app/ruff.toml
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      #- MONGO_URI=mongodb://root:example@db:27017/
    #restart: unless-stopped
    #depends_on:
      #- db

  frontend:
    working_dir: /code
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    stdin_open: true
    tty: true

# db:
    #image: mongo:6.0
    #ports:
    #  - "27017:27017"
    #volumes:
     # - mongodb_data:/data/db
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example

#volumes:
  #mongodb_data: