services:
  backend:
    build: ./backend
    volumes:
       - ./backend/app:/app/app
       - ./test_project:/code/
       - /tmp:/tmp
       - ./backend/ruff.toml:/app/ruff.toml
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      disable: true
     

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
