services:
  backend:
    build: ./backend
    volumes:
       - ./backend:/app
       - ./test_project:/code/
       - ./backend/ruff.toml:/app/ruff.toml
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONPATH=/app

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"