services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./test_projects:/code  # Mount the parent directory containing all projects
      - ./backend/ruff.toml:/app/ruff.toml
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped  # Prevents unwanted recreations

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules inside container
      - ./frontend/ruff.toml:/app/ruff.toml  # Mount the ruff.toml configuration file
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development  # Set the environment to development
    command: npm run dev  # Start the Next.js development server